/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyBackdrop {}
  interface MyModal {
    'open': () => Promise<void>;
  }
  interface SlideMenu {
    'expand': () => Promise<void>;
  }
}

declare global {


  interface HTMLMyBackdropElement extends Components.MyBackdrop, HTMLStencilElement {}
  var HTMLMyBackdropElement: {
    prototype: HTMLMyBackdropElement;
    new (): HTMLMyBackdropElement;
  };

  interface HTMLMyModalElement extends Components.MyModal, HTMLStencilElement {}
  var HTMLMyModalElement: {
    prototype: HTMLMyModalElement;
    new (): HTMLMyModalElement;
  };

  interface HTMLSlideMenuElement extends Components.SlideMenu, HTMLStencilElement {}
  var HTMLSlideMenuElement: {
    prototype: HTMLSlideMenuElement;
    new (): HTMLSlideMenuElement;
  };
  interface HTMLElementTagNameMap {
    'my-backdrop': HTMLMyBackdropElement;
    'my-modal': HTMLMyModalElement;
    'slide-menu': HTMLSlideMenuElement;
  }
}

declare namespace LocalJSX {
  interface MyBackdrop extends JSXBase.HTMLAttributes<HTMLMyBackdropElement> {}
  interface MyModal extends JSXBase.HTMLAttributes<HTMLMyModalElement> {}
  interface SlideMenu extends JSXBase.HTMLAttributes<HTMLSlideMenuElement> {}

  interface IntrinsicElements {
    'my-backdrop': MyBackdrop;
    'my-modal': MyModal;
    'slide-menu': SlideMenu;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


